### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [enowars/enochecker_core#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.2.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary enochecker-core -w /tmp/ext enochecker-core==0.2.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting enochecker-core==0.2.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/ce4/adb3e91ff4f15/enochecker_core-0.2.0.tar.gz (1.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-3q9epk5k/enochecker-core/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-3q9epk5k/enochecker-core/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-3q9epk5k/enochecker-core/pip-egg-info
         cwd: /tmp/pip-wheel-3q9epk5k/enochecker-core/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-3q9epk5k/enochecker-core/setup.py", line 6, in <module>
        with open("requirements.txt", "r") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Trolldemorted** [comment]
Thanks!

So `pip3 wheel` requires a manifest while `python3 setup.py sdist bdist_wheel` (which our CI and release pipelines use) does not?

**Comment by mauricesvp** [comment]
I guess we can add a manifest file with `include requirements.txt`, I don't see any other files that could be missing?

**Comment by mauricesvp** [comment]
Also note that this only seems to be problematic using the `--no-binary` flag, which is sort of out of scope as far as the use-case of this repo goes.

**Comment by thatch** [comment]
Some companies and distros want to compile everything from source, so pass `--no-binary :all:`, for example https://github.com/dropbox/dbx_build_tools/blob/master/build_tools/py/vpip.py#L311

I added a PR that is one way of fixing it.
